version: "3.7"

networks:
  app_net:
    driver: bridge

services:

  node:
    container_name: node
    build: .
    ports:
      - 7000:3000
    volumes:
      - ./:/opt/node-api
    depends_on:
      - mysql
    networks:
      - app_net

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppwd
    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/var/log/mysql
    networks:
      - app_net

volumes:
  data:
  logs:
